version: '3'
services:
  mongo:
    image: "mongo:latest"
  redis:
    image: "redis:alpine"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.backend
    environment:
      - APP_ENV=dev
    depends_on:
     - mongo
     - redis
    ports:
      - "40001:40001"
    volumes:
     - ./backend:/code
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
      - APP_BACKEND_URL=backend:40001
      - APP_FRONTEND_PORT=40002
    depends_on:
      - backend
    ports:
      - "40002:40002"
    volumes:
      - ./frontend:/app/src
  worker:
    build:
      context: backend
      dockerfile: Dockerfile.worker
    environment:
      - APP_ENV=dev
    depends_on:
     - mongo
     - redis
    volumes:
     - ./backend:/code
